### ISSUE TITLE
the data format is not very clear for the beginers. 

### ISSUE THREAD

**Issue by Germany2010** [paypal/autosklearn-zeroconf#12]
As it mentioned in the https://github.com/paypal/autosklearn-zeroconf

Data Format
The code uses a pandas dataframe format to manage the data. It is stored in the HDF5 .h5 file for convenience. (Python module "tables")

It is a bit unclear for me. when I check my data with the example data Adult.h5, the structure looks different. 

Is there any rules or suggestions, that users have to follow? thank you.

**Comment by Motorrat** [comment]
Hi, @Germany2010, the zerconf is not necessarily targeted at total beginners. Please see the disclaimer in the LICENSE.txt  It is offered completely AS IS. As you can see in the LICENSE.txt 

> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED

You are expected to master Python and know your data (structures). 

Having said that, as you correctly quote HDF5 is used just for convenience. Please check whether you could load your data as a dataframe with your own code instead and use it directly substituting this line
https://github.com/paypal/autosklearn-zeroconf/blob/bf431d3a44874c5627b0406ee68f250219a1890c/bin/zeroconf.py#L117

**Comment by Germany2010** [comment]
@Motorrat thank you very much for the reply. It's pretty clear now. 

p.s.
"beginers" here means the new users for this nice model^^  The model is really nice and powerful. Thank you for the contribution.
